### PR TITLE
feat: initially bring up layout page

### PR DESCRIPTION
**Pull request by q1zhen**

### CODE REVIEW

**Comment by qwerzl** [comment]
Sorry for the late reply, been busy these days.

**Comment by qwerzl** [comment]
Netlify's bots are weirdly buggy. @q1zhen could you do me a flavor by running `git commit -m "retrigger checks" --allow-empty` in both the PR branches?

**Comment by at-wr** [comment]
lol, the commit "retrigger checks" failed passing the check `Conventional commits check`

**Comment by q1zhen** [comment]
> lol, the commit "retrigger checks" failed passing the check `Conventional commits check`

Yeah I am fully aware of that. This is just to reload the bot, though.

**Comment by qwerzl** [comment]
looks like a weird bug on netlify. Gimme some time, I'm looking into that.

**Comment by qwerzl** [comment]
Done. Sorry for the late reply, really didn't expect it was `nitro`'s bug...

**Pull request merged**
