### PR TITLE
feat(clubList): show dissolved clubs at the end of clubList

### PR DESCRIPTION
**Pull request by at-wr**
It might be hard to review the code lol

## Related Issue

#532

### CODE REVIEW

**Comment by qwerzl** [comment]
It might be better to just sort the `club` before `filteredClubs` is defined. Define a custom sort function, then `club.sort(someCustomSortFunc)`. Check this out: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort.

edit: sorry didn't notice you've already used `.sort()`. Still, it's better to directly sort `club`. @at-wr

**Comment by at-wr** [comment]
> It might be better to just sort the `club` before `filteredClubs` is defined. Define a custom sort function, then `club.sort(someCustomSortFunc)`. Check this out: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort.
> 
> edit: sorry didn't notice you've already used `.sort()`. Still, it's better to directly sort `club`. @at-wr

@qwerzl Hey, I defined a new function `sortClubs` and simplified the searching logic which can also optimize the performance

**Comment by qwerzl** [comment]
@at-wr Fixed some code. Always remember not to use `any` type, not to assign redundant variables and not to copy-paste from GPT. But well done in general.

**Comment by qwerzl** [comment]
Closes #532.

**Pull request merged**
