### PR TITLE
feat(manage): add CAS time dashboard on activity record

### PR DESCRIPTION
**Pull request by at-wr**
## Overview
Added a CAS time dashboard to the Activity Record, allowing for display of individual, combined, and total sums across all records.

## Links
Related Issue: #633

### CODE REVIEW

**Comment by qwerzl** [comment]
@at-wr Do you have the permission to merge?

**Comment by at-wr** [comment]
> @at-wr Do you have the permission to merge?

Actually no lol

**Comment by qwerzl** [comment]
@at-wr You should have it now. Netlify has this stupid bug with clerk causing infinite redirections so currently you'll not be able to test your code in PRs. Test it thoroughly in staging and create a release since this is a new minor feature.

**Comment by qwerzl** [comment]
And don't forget to write changesets. I'd recommend you to write it in this PR.

**Pull request merged**
