### PR TITLE
Change Layout of Clubpage

### PR DESCRIPTION
**Pull request by ETwilight**
Layout for logo and club name is changed to left-right layout instead of up-down layout.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
image
Poor responsive layout

**Comment by Josh-Cena** [comment]
image
Actually the original design's not that bad, considering it's purely decorative. WDYT?

**Comment by ETwilight** [comment]
> image
> Actually the original design's not that bad, considering it's purely decorative. WDYT?

On selfphones not weird but still quite weird when being opened on computer.

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Swap title and logo to align all text on left

**Comment by Josh-Cena** [comment]
> > image
> > Actually the original design's not that bad, considering it's purely decorative. WDYT?
> 
> On selfphones not weird but still quite weird when being opened on computer.

image
Consider this case in which the top banner is purely decorative. We don't actually care what's the actual content—we may encourage clubs to upload a properly sized banner picture in the future.

**Pull request closed without merging**
